# This is a workflow that is manually triggered to deploy supported components other than applications

name: Manual Deployment

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      Version:
        description: |
          Version to deploy:
        default: 'Latest'
        required: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      Version: ${{ github.event.inputs.Version }}
      KUBECONFIG_FILE: ${{ secrets.MONGOKUBECONFIG }}
      KUBECONFIG: kubeconfig
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1

      - name: Get kubectl
        run: |
          curl -LO https://dl.k8s.io/release/v1.20.0/bin/linux/amd64/kubectl
          chmod +x kubectl

      - name: install make
        run: |
          sudo apt install make
          
      - name: install helm
        run: |
          sudo snap install helm --classic  
      #     curl https://baltocdn.com/helm/signing.asc
      #     sudo apt-key add
      #     sudo apt-get install apt-transport-https --yes echo "deb https://baltocdn.com/helm/stable/debian/ all main"
      #     sudo tee /etc/apt/sources.list.d/helm-stable-debian.list 
      #     sudo apt-get update 
      #     sudo apt-get install helm   
          
      - name: make provision-hostpath
        env:
          KUBECONFIG_FILE: ${{ secrets.MONGOKUBECONFIG }}
        run: |
          make provision-hostpath
      
      - name: make rke-yaml
        env:
          KUBECONFIG_FILE: ${{ secrets.MONGOKUBECONFIG }}
        run: |
          make rke-yaml
      
      # - name: Save kubeconfig
      #   env:
      #     KUBECONFIG_FILE: ${{ secrets.MONGOKUBECONFIG }}
      #   run: |
      #     echo ${KUBECONFIG_FILE} | base64 -d  > ${KUBECONFIG}

      # - name: Apply deployment
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB }}
      #   run: |
      #     sed -i "s/IMAGE_TAG/${Version}/g" manifests/mongodb-manifets.yaml
      #     ./kubectl kustomize manifests/ | ./kubectl apply -f -
